Repository DrKJeff16/wezterm-types, pull requests merged in 2025-08, with the labels that each got.

#32 Add demonstrative GIF to `README.md`
  README.md
Labels: documentation, enhancement

#33 [REFACTOR] Moved files, removed a lot of useless types
  .github/CODEOWNERS
  lua/types/config.lua
  lua/types/init.lua
  lua/types/objects/color.lua
  lua/types/objects/local-process-info.lua
  lua/types/objects/mux-tab.lua
  lua/types/objects/mux-window.lua
  lua/types/objects/pane-information.lua
  lua/types/objects/pane.lua
  lua/types/objects/tab-information.lua
  lua/types/objects/time.lua
  lua/types/objects/tls-domain-client.lua
  lua/types/objects/tls-domain-server.lua
  lua/types/objects/window.lua
  lua/types/objects/wsl-domain.lua
  lua/types/wezterm/color.lua
  lua/types/wezterm/gui.lua
  lua/types/wezterm/init.lua
  lua/types/wezterm/mux.lua
  lua/types/wezterm/nerdfonts.lua
  lua/types/wezterm/plugin.lua
  lua/types/wezterm/procinfo.lua
  lua/types/wezterm/serde.lua
  lua/types/wezterm/time.lua
  lua/types/wezterm/url.lua
Labels: documentation, enhancement

#30 Partial overhaul for `types/config.lua`
  lua/types/config.lua
  lua/types/init.lua
Labels: documentation, enhancement, help wanted, new-types, work-in-progress

#36 feat: Add credits to collaborators and maintainers in `README.md`.
  README.md
Labels: documentation, enhancement

#35 `.luarc.json` cleanup
  .luarc.json
Labels: enhancement

#41 [CONFIG] Further `Config` class documentation
  lua/types/config.lua
Labels: documentation, enhancement

#43 feat: Add `.editorconfig` file
  .editorconfig
Labels: enhancement

#40 feat: add config.leader and document it
  lua/types/config.lua
  lua/types/enum/key-assignment.lua
  lua/types/init.lua
Labels: documentation, missing-types, needs-review

#38 [REPO] Issue Templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/1-missing_types.yml
  .github/ISSUE_TEMPLATE/2-feature_request.yml
  .github/ISSUE_TEMPLATE/3-lazydev-bug.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement

#49 Update issue templates, due to ownership transfer
  .github/ISSUE_TEMPLATE/1-missing_types.yml
  .github/ISSUE_TEMPLATE/2-feature_request.yml
  .github/ISSUE_TEMPLATE/3-lazydev-bug.yml
Labels: enhancement

#50 Updated `README.md`
  README.md
Labels: documentation, announcement

#53 Multiple fixes and improvements.
  lua/types/config.lua
  lua/types/init.lua
  lua/types/wezterm/init.lua
Labels: bug, documentation, enhancement

#60 [FEAT] TOC in `README.md`
  README.md
Labels: documentation, enhancement

#61 [CRITICAL] Moved `types/` dir to `wezterm/types/`
  .github/CODEOWNERS
  README.md
  lua/types/enum/init.lua
  lua/types/events/init.lua
  lua/types/objects/init.lua
  lua/wezterm/types/config.lua
  lua/wezterm/types/enum/copy-mode-assignment.lua
  lua/wezterm/types/enum/init.lua
  lua/wezterm/types/enum/key-assignment.lua
  lua/wezterm/types/events/gui.lua
  lua/wezterm/types/events/init.lua
  lua/wezterm/types/events/multiplexer.lua
  lua/wezterm/types/events/window.lua
  lua/wezterm/types/init.lua
  lua/wezterm/types/objects/color.lua
  lua/wezterm/types/objects/exec-domain.lua
  lua/wezterm/types/objects/init.lua
  lua/wezterm/types/objects/local-process-info.lua
  lua/wezterm/types/objects/mux-domain.lua
  lua/wezterm/types/objects/mux-tab.lua
  lua/wezterm/types/objects/mux-window.lua
  lua/wezterm/types/objects/pane-information.lua
  lua/wezterm/types/objects/pane.lua
  lua/wezterm/types/objects/spawn-command.lua
  lua/wezterm/types/objects/ssh-domain.lua
  lua/wezterm/types/objects/tab-information.lua
  lua/wezterm/types/objects/time.lua
  lua/wezterm/types/objects/tls-domain-client.lua
  lua/wezterm/types/objects/tls-domain-server.lua
  lua/wezterm/types/objects/window.lua
  lua/wezterm/types/objects/wsl-domain.lua
  lua/wezterm/types/wezterm/color.lua
  lua/wezterm/types/wezterm/gui.lua
  lua/wezterm/types/wezterm/init.lua
  lua/wezterm/types/wezterm/mux.lua
  lua/wezterm/types/wezterm/nerdfonts.lua
  lua/wezterm/types/wezterm/plugin.lua
  lua/wezterm/types/wezterm/procinfo.lua
  lua/wezterm/types/wezterm/serde.lua
  lua/wezterm/types/wezterm/time.lua
  lua/wezterm/types/wezterm/url.lua
Labels: documentation, enhancement, needs-review

#62 Added `greetings` GitHub Action
  .github/workflows/greetings.yml
Labels: enhancement

#69 fix(wezterm): overhaul
  lua/wezterm/types/config.lua
  lua/wezterm/types/enum/key-assignment.lua
  lua/wezterm/types/wezterm.lua
  lua/wezterm/types/wezterm/color.lua
  lua/wezterm/types/wezterm/serde.lua
Labels: documentation, enhancement, needs-review, work-in-progress

#70 fix(wezterm): filling out `wezterm.lua` and other files
  lua/wezterm/types/config.lua
  lua/wezterm/types/enum/key-assignment.lua
  lua/wezterm/types/objects/mux-tab.lua
  lua/wezterm/types/objects/spawn-command.lua
  lua/wezterm/types/objects/tab-information.lua
  lua/wezterm/types/wezterm.lua
  lua/wezterm/types/wezterm/color.lua
  lua/wezterm/types/wezterm/gui.lua
  lua/wezterm/types/wezterm/mux.lua
  lua/wezterm/types/wezterm/plugin.lua
  lua/wezterm/types/wezterm/procinfo.lua
  lua/wezterm/types/wezterm/serde.lua
  lua/wezterm/types/wezterm/time.lua
Labels: documentation, enhancement, new-types, needs-review
